# Generated by Django 5.2.8 on 2025-11-22 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('comunicado', 'Comunicado'), ('advertencia', 'Advertencia'), ('recordatorio', 'Recordatorio')], default='comunicado', max_length=20)),
                ('destinatario_uid', models.TextField()),
                ('estudiante_id', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('enviada', models.BooleanField(default=False)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['destinatario_uid'], name='notificatio_destina_f92e1e_idx'), models.Index(fields=['estudiante_id'], name='notificatio_estudia_5a368e_idx'), models.Index(fields=['tipo'], name='notificatio_tipo_0f00eb_idx'), models.Index(fields=['-fecha_creacion'], name='notificatio_fecha_c_5e8380_idx')],
            },
        ),
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('salon_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grado', models.TextField()),
                ('seccion', models.TextField()),
                ('nombre', models.TextField()),
                ('teacher_uid', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'salones',
                'indexes': [models.Index(fields=['grado', 'seccion'], name='salones_grado_8fa256_idx'), models.Index(fields=['teacher_uid'], name='salones_teacher_92c80c_idx'), models.Index(fields=['activo'], name='salones_activo_7dc77c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('grado', models.TextField()),
                ('padre_uid', models.TextField()),
                ('profesor_uid', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('datos_medicos', models.JSONField(blank=True, null=True)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('salon', models.ForeignKey(db_column='salon_id', on_delete=django.db.models.deletion.CASCADE, to='api.salones')),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_uid', models.TextField()),
                ('rol', models.CharField(choices=[('director', 'Director'), ('padre', 'Padre'), ('profesor', 'Profesor'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=20)),
                ('tipo', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('campus_name', models.TextField(blank=True, null=True)),
                ('address_full', models.TextField(blank=True, null=True)),
                ('address_short', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_attendance',
                'indexes': [models.Index(fields=['staff_uid'], name='staff_atten_staff_u_22b18a_idx'), models.Index(fields=['fecha'], name='staff_atten_fecha_a8ae06_idx'), models.Index(fields=['rol'], name='staff_atten_rol_8a242a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_uid', models.TextField()),
                ('grado', models.TextField()),
                ('seccion', models.TextField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teacher_assignments',
                'indexes': [models.Index(fields=['teacher_uid'], name='teacher_ass_teacher_217a7a_idx'), models.Index(fields=['grado', 'seccion'], name='teacher_ass_grado_910e58_idx'), models.Index(fields=['activo'], name='teacher_ass_activo_6fc2b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(choices=[('director', 'Director'), ('padre', 'Padre'), ('profesor', 'Profesor'), ('admin', 'Admin'), ('staff', 'Staff')], default='padre', max_length=20)),
                ('nombre', models.TextField()),
                ('correo', models.TextField(unique=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuarios',
                'indexes': [models.Index(fields=['rol'], name='usuarios_rol_936bfb_idx'), models.Index(fields=['activo'], name='usuarios_activo_3d49ab_idx'), models.Index(fields=['nombre'], name='usuarios_nombre_1ca585_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('asistencia_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('registrado_por_uid', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('presente', 'Presente'), ('tarde', 'Tarde'), ('falta', 'Falta'), ('justificado', 'Justificado')], max_length=20, null=True)),
                ('profesor_uid', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_aux', models.TextField(blank=True, null=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_registro_profesor', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro_aux', models.DateTimeField(blank=True, null=True)),
                ('grado', models.TextField(blank=True, null=True)),
                ('seccion', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('campus_name', models.TextField(blank=True, null=True)),
                ('address_full', models.TextField(blank=True, null=True)),
                ('address_short', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='api.estudiantes')),
            ],
            options={
                'db_table': 'attendances',
                'indexes': [models.Index(fields=['student'], name='attendances_student_57d8b0_idx'), models.Index(fields=['fecha'], name='attendances_fecha_4787dd_idx'), models.Index(fields=['registrado_por_uid'], name='attendances_registr_5b0de0_idx'), models.Index(fields=['status'], name='attendances_status_dae783_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='estudiantes',
            index=models.Index(fields=['salon'], name='estudiantes_salon_i_4c2026_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiantes',
            index=models.Index(fields=['padre_uid'], name='estudiantes_padre_u_595f77_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiantes',
            index=models.Index(fields=['profesor_uid'], name='estudiantes_profeso_196a26_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiantes',
            index=models.Index(fields=['activo'], name='estudiantes_activo_150ef2_idx'),
        ),
    ]
